// flow-typed signature: 1d07fdf7fd6b717899ee9f0c9e1de274
// flow-typed version: <<STUB>>/typeface-roboto_v0.0.41/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-roboto'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-roboto' {
  declare module.exports: any;
}
